### ISSUE TITLE
Skip/Include only certain MIME types for gzip?

### ISSUE THREAD

**Issue by schungx** [mikegore1000/SqueezeMe#2]
First of all, let me say that this piece is wonderful.  Works like a charm with no fuss.

One imperfection, though, is the inability to detect certain MIME types that should not be compressed.  For example, `image/jpeg`, `image/gif`, `video/mp4`, `audio/mp3` etc. shouldn't be bothered.

It should be simple enough to allow the user to input a list of MIME types, and detect these MIME types in the header and skip compression.

Thanks a whole lot for your work!

**Comment by schungx** [comment]
Incidentally, since the module is in a unique position to have both the original data stream as well as the compressed data stream on-hand, it should be simple to make sure that the compressed stream is only sent if the compressed stream is smaller than the original stream by at least a certain %.

Definitely not send the compressed stream if it is larger or same size as the original stream as the client will be incurring decompression costs for nothing.

**Comment by mikegore1000** [comment]
Thanks for the feedback, much appreciated.

Implementing a exclusion filter based on the MIME types on the Accept header would be pretty simple do achieve with the current implementation.

However, I believe in order to do this, looking at the Content-Type header would make more sense.  The main consideration here though is performance.

At present the code sets the response body stream before passing the context to the next middleware.  If the code was changed to compress after the next middleware is called it'll mean we have to take an additional stream copy, so I'll need to benchmark to make sure this doesn't degrade performance too much.

My main use of the library on a day to day basis has been for JSON payloads (via ASP.NET Web API), so excluding MIME types hasn't been a requirement so far.  Would be interested to get some additional context around how you are using it (though the scenarios you outline make sense).

**Comment by schungx** [comment]
If I get some time, I can probably take a hack at it and give you a PR.

I hear your point; I use this library on a self-hosted OWIN with primarily JSON payloads.  However, it also compresses all the web site files going out of the FileServer module with no fuss!  A big win!

My program exposes both a website interface plus the web api's that drive the data.  Having one single module does all the gzipping is awesome!

The only one odd thing is PNG's, GIF's and JPG's are all compressed.

**Comment by schungx** [comment]
I've modified the code to check an "excluded" MIME type list.  Unfortunately, due to the fact that the content type is not set until lower in the middleware chain.

Which means that, the current way I do it is: detect an excluded MIME type, then decompress the resultant stream.  _akem_

Note this will not affect your Web API's at all since they will mostly return `application/json` which is definitely not in the excluded list.  However, if you ever want to return an image from your API, then this feature will come in handy.  The pitfall is, of course, you get to waste all those cycles compressing and decompressing the image files.

Dunno how to make a pull request yet... so maybe you can surf to my fork to check it out.

**Comment by mikegore1000** [comment]
Thanks for the pull request.  Just looking through the code now and I think it would be better if we didn't decompress the compressed stream to handle this.

It's probably better to trade off memory rather than CPU - therefore what I'm thinking the best way forward is:
1. Default behavior is no exclusions are supplied.  Everything is compressed - this way the current approach can be used.
2. If an exclusion list is supplied then we don't compress when delegating to the next middleware and we compress the response when required.  It means an extra memory stream, but this should be more efficient than compressing & decompressing when it isn't required, especially with larger responses.

**Comment by mikegore1000** [comment]
Feature has now been implemented and is available on NuGet in version 1.1.29.

Thank you for raising the feature, hope it helps!

**Comment by schungx** [comment]
Wonderful!

**Comment by schungx** [comment]
Another option is to provide a exclusion extensions list. This should work because the request URL is well formed from the very beginning. This is less robust than check content type though.

**Comment by mikegore1000** [comment]
I did think about that, but I need to be able to support extensionless URLs and also if a client requests multiple MIME types.  Made more sense to me to let the web framework handle any content negotiation issues.

The nice thing about the current implementation is that it should be as optimised as it can be based on whether you supply additional config or not.

Hope this gives you what you need.

**Comment by schungx** [comment]
Yup.  Great stuff.  The current implementation is optimal for most large assets (such as videos, images).  There is more memory pressure for static pages and web api responses, but those are usually relatively short (at least much smaller compared to an image).  CPU usage is unchanged since there is no additional workload done.
